import re
import sqlite3
from pathlib import Path
from typing import Any
from graph.state import AgentState

def sql_executor(state: AgentState) -> dict[str, Any]:
    """
    Executes the drafted SQL query against the temporary SQLite database.

    This tool attempts to run the SQL code generated by the SQL Drafter.
    It uses the database located at state["db_path"].

    Args:
        state (AgentState): The current state containing 'sql_query' 
            and 'db_path'.

    Returns:
        dict: A dictionary updating 'raw_data' and 'sql_error'.
    """
    db_path = state["db_path"]
    query = state.get("sql_query", "")
    
    if not query:
        return {"sql_error": "No SQL query provided to execute."}
        
    # Normalize whitespace for reliable keyword detection
    normalized = re.sub(r'\s+', ' ', query).strip()
    upper_query = normalized.upper()
    
    # Basic SQL Injection Prevention (Enforce SELECT only)
    if not upper_query.startswith("SELECT"):
        return {"sql_error": "Security Error: Only SELECT queries are allowed."}
    
    forbidden_keywords = ["DROP", "DELETE", "INSERT", "UPDATE", "ALTER", "ATTACH", "DETACH"]
    for kw in forbidden_keywords:
        # Use word boundary regex for reliable detection
        if re.search(rf'\b{kw}\b', upper_query):
            return {"sql_error": f"Security Error: The keyword '{kw}' is forbidden."}
    
    try:
        # Use pathlib for cross-platform URI construction (fixes Windows backslash issue)
        db_uri = f"{Path(db_path).resolve().as_uri()}?mode=ro"
        
        with sqlite3.connect(db_uri, uri=True) as conn:
            # Use Row factory to get dictionaries instead of tuples for better LLM context
            conn.row_factory = sqlite3.Row 
            cursor = conn.cursor()

            cursor.execute(query)
            rows = cursor.fetchall()
            
            # Convert sqlite3.Row objects to standard dictionaries
            data = [dict(row) for row in rows]
        
        # Success: Update raw_data and clear any previous error
        return {
            "raw_data": data,
            "sql_error": ""
        }
        
    except Exception as e:
        # Failure: Capture error for the correction loop
        return {
            "sql_error": str(e),
            "raw_data": []
        }
