import sqlite3
import os
from graph.state import AgentState

def sql_executor(state: AgentState):
    """
    Executes the drafted SQL query against the temporary SQLite database.

    This tool attempts to run the SQL code generated by the SQL Drafter.
    It uses the database located at 'state.db_path'.

    Args:
        state (AgentState): The current state containing 'sql_query' 
            and 'db_path'.

    Returns:
        dict: A dictionary updating 'raw_data' and 'sql_error'.
    """
    db_path = state.db_path
    query = state.sql_query
    
    if not query:
        return {"sql_error": "No SQL query provided to execute."}
        
    # Basic SQL Injection Prevention (Enforce SELECT only)
    upper_query = query.upper()
    forbidden_keywords = ["DROP", "DELETE", "INSERT", "UPDATE", "ALTER", "ATTACH", "DETACH"]
    if not upper_query.strip().startswith("SELECT"):
        return {"sql_error": "Security Error: Only SELECT queries are allowed."}
    for kw in forbidden_keywords:
        if f" {kw} " in f" {upper_query} ":
            return {"sql_error": f"Security Error: The keyword '{kw}' is forbidden."}
    
    try:
        # Use context manager for safe DB connection handling
        # Enforce read-only mode at the database engine level
        # Convert path to absolute URI for read-only mode
        db_uri = f"file:{os.path.abspath(db_path)}?mode=ro"
        
        with sqlite3.connect(db_uri, uri=True) as conn:
            # Use Row factory to get dictionaries instead of tuples for better LLM context
            conn.row_factory = sqlite3.Row 
            cursor = conn.cursor()

            
            cursor.execute(query)
            rows = cursor.fetchall()
            
            # Convert sqlite3.Row objects to standard dictionaries
            data = [dict(row) for row in rows]
        
        # Success: Update raw_data and clear any previous error
        return {
            "raw_data": data,
            "sql_error": ""
        }
        
    except Exception as e:
        # Failure: Capture error for the correction loop
        return {
            "sql_error": str(e),
            "raw_data": []
        }
